# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    indices:
        - name: accounts
          class: App\Entity\Account
          enable_serializer_groups: true
