<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * TransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function returnTransactionsSince($timestamp){
        $qb = $this->createQueryBuilder('t');

        $qb
            ->where('t.timestamp > :timestamp')
            ->setParameter('timestamp', $timestamp)
            ->orderBy('t.timestamp', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
