# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/3.4/security/entity_provider.html#configure-security-to-load-from-your-entity
    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # https://symfony.com/doc/3.4/security/multiple_user_providers.html
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    toto: { password: tototo }
        user_db:
            entity: { class: AppBundle\Entity\Users, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: chain_provider
            logout_on_user_change: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                provider: user_db
            # https://symfony.com/doc/3.4/security.html#logging-out
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:     '%secret%'
                lifetime:   604800
                path:       /
            
        secured_area:
            pattern: ^/
            provider: chain_provider
            logout_on_user_change: true
            # https://symfony.com/doc/3.4/security/csrf_in_login_form.html
            form_login:
                provider: user_db
            # https://symfony.com/doc/3.4/security.html#logging-out
            logout:
                path:   /logout
                target: /
    
    access_control:
    - { path: ^/register, roles: ROLE_SUPER_ADMIN }
    - { path: ^/stock/details, roles: ROLE_STOCK }
    - { path: ^/stock/ajout, roles: ROLE_STOCK }
    - { path: ^/preparation, roles: ROLE_BUREAU }
    - { path: ^/purchase, roles: ROLE_INTRO }

    role_hierarchy:
        ROLE_BUREAU:    ROLE_INTRO
        ROLE_VVP:     ROLE_BUREAU
        ROLE_FEE:     ROLE_BUREAU
        ROLE_COM:       ROLE_BUREAU
        ROLE_SECRET:    ROLE_BUREAU
        ROLE_STOCK:     ROLE_BUREAU
        ROLE_TRESO:     ROLE_BUREAU
        ROLE_ALL:       [ROLE_STOCK, ROLE_TRESO, ROLE_SECRET, ROLE_COM]
        ROLE_ADMIN:     ROLE_ALL
        ROLE_SUPER_ADMIN: ROLE_ADMIN
